on:
  push:
    branches:
      - main
  pull_request:
  release:
    types:
      - created

name: CI
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - run: sudo bash ./install-zig.sh
        env:
          ZIG_VERSION: "master"

      - run: make install
      - run: make release

      - name: Upload build
        uses: actions/upload-pages-artifact@v1
        with:
          name: public
          path: ./web

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1